/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancems_with_prepared22;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;

/**
 *
 * @author Iqbal-Asi
 */
public class AttendFrame extends javax.swing.JFrame {

    ConnectClass c;

    /**
     * Creates new form AttendFrame
     */
    public AttendFrame() {
        initComponents();
        c = new ConnectClass();

        //Logo
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/attendancems_with_prepared22/Project_Images/Logo.png")));
        //Disabling size
        setResizable(false);

        //Title
        setTitle("Attendance Panel");

        TeacherInternalFrame tf = new TeacherInternalFrame();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(tf);
        tf.show();

        searchCombo();

        FullAttendancejTable.setSelectionForeground(Color.WHITE);

        clearing();
    }

    /**
     * Filling ComboBox for search
     */
    public void searchCombo() {

        try {
            ResultSet rs = c.st.executeQuery("select column_name from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'std_attend' and TABLE_SCHEMA = 'dbo'");
            while (rs.next()) {
                jComboBox1.addItem(rs.getString(1));
            }

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    /**
     * Clearing table dAta
     */
    public void clearing() {
        /**
         * Clearing Rows from jTable1
         */
        DefaultTableModel dt = (DefaultTableModel) FullAttendancejTable.getModel();
        int rowCount = dt.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dt.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                ImageIcon icon = new ImageIcon((getClass().getResource("/attendancems_with_prepared22/Project_Images/FrameBG.png")));
                Image image = icon.getImage();
                g.drawImage(image, 0,0,getWidth(),getHeight(), this);
            }
        };
        jPanelReport = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        FullAttendancejTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabelReportPanelBG = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1batchCode = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        HorizontalPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jDesktopPane1.setBackground(null);
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(800, 540));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(800, 540));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(800, 550));

        jPanelReport.setMaximumSize(new java.awt.Dimension(640, 500));
        jPanelReport.setMinimumSize(new java.awt.Dimension(640, 500));
        jPanelReport.setPreferredSize(new java.awt.Dimension(640, 500));
        jPanelReport.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search");
        jPanelReport.add(jLabel1);
        jLabel1.setBounds(140, 80, 100, 30);

        jTextField1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanelReport.add(jTextField1);
        jTextField1.setBounds(250, 80, 260, 30);

        jComboBox1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jPanelReport.add(jComboBox1);
        jComboBox1.setBounds(540, 80, 190, 30);

        jScrollPane1.setBorder(null);
        jScrollPane1.setAlignmentX(1.0F);
        jScrollPane1.setAlignmentY(1.0F);
        jScrollPane1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jScrollPane1.setOpaque(false);

        FullAttendancejTable.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        FullAttendancejTable.setForeground(new java.awt.Color(255, 255, 255));
        FullAttendancejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attend Date", "Student ID", "Student Name", "Batch Code", "Book", "Book Session", "Attendance Status"
            }
        ));
        FullAttendancejTable.setOpaque(false);
        ((DefaultTableCellRenderer)FullAttendancejTable.getDefaultRenderer(Object.class)).setOpaque(false);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        FullAttendancejTable.setShowGrid(false);
        FullAttendancejTable.setGridColor(new java.awt.Color(255, 255, 255));
        FullAttendancejTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        FullAttendancejTable.setOpaque(false);
        jScrollPane1.setViewportView(FullAttendancejTable);

        jPanelReport.add(jScrollPane1);
        jScrollPane1.setBounds(90, 150, 620, 290);

        jButton4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/excel.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelReport.add(jButton4);
        jButton4.setBounds(320, 470, 110, 30);

        jButton5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/pdf.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelReport.add(jButton5);
        jButton5.setBounds(450, 470, 100, 30);

        jLabelReportPanelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/FrameBG.png"))); // NOI18N
        jLabelReportPanelBG.setMaximumSize(new java.awt.Dimension(640, 500));
        jLabelReportPanelBG.setMinimumSize(new java.awt.Dimension(640, 500));
        jLabelReportPanelBG.setPreferredSize(new java.awt.Dimension(640, 500));
        jPanelReport.add(jLabelReportPanelBG);
        jLabelReportPanelBG.setBounds(0, 0, 800, 550);

        jDesktopPane1.add(jPanelReport);
        jPanelReport.setBounds(0, 0, 800, 550);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/FrameBG.png"))); // NOI18N
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 550);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(200, 0, 800, 550);

        jPanel2.setMaximumSize(new java.awt.Dimension(190, 550));
        jPanel2.setMinimumSize(new java.awt.Dimension(190, 550));
        jPanel2.setPreferredSize(new java.awt.Dimension(190, 550));
        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/Student.png"))); // NOI18N
        jButton1.setText("  Student");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setEnabled(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 150, 160, 52);

        jButton2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/Group.png"))); // NOI18N
        jButton2.setText("     Class");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setEnabled(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 220, 160, 50);

        jButton3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/report.png"))); // NOI18N
        jButton3.setText("Report");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(20, 290, 160, 50);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Batch Code");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 20, 120, 40);

        jLabel1batchCode.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1batchCode.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel1batchCode);
        jLabel1batchCode.setBounds(20, 70, 170, 30);

        jButton6.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/Setting.png"))); // NOI18N
        jButton6.setText("Setting");
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(20, 360, 160, 50);

        jButton7.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/exit.png"))); // NOI18N
        jButton7.setText("Exit");
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(20, 430, 160, 50);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/back.png"))); // NOI18N
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(20, 490, 40, 30);

        HorizontalPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attendancems_with_prepared22/Project_Images/HorizontalPanelBG.png"))); // NOI18N
        HorizontalPanel.setRequestFocusEnabled(false);
        jPanel2.add(HorizontalPanel);
        HorizontalPanel.setBounds(0, 0, 200, 550);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 550);

        setSize(new java.awt.Dimension(1016, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StudentJInternalFrame sif = new StudentJInternalFrame();
        jDesktopPane1.add(sif);
        sif.show();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ClassJInternalFrame cif = new ClassJInternalFrame();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(cif);
        cif.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        jDesktopPane1.removeAll();
        jDesktopPane1.add(jPanelReport);
        clearing();
        jPanelReport.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        /**
         * Excel Report
         */

        JFileChooser j = new JFileChooser();
        int i = j.showSaveDialog(this);
        System.out.println(i);
        if (i == 0) {
            try {
                PrintWriter p = new PrintWriter(j.getSelectedFile() + ".csv");

                p.println(FullAttendancejTable.getColumnName(0) + "," + FullAttendancejTable.getColumnName(1) + "," + FullAttendancejTable.getColumnName(2) + "," + FullAttendancejTable.getColumnName(3) + "," + FullAttendancejTable.getColumnName(4) + "," + FullAttendancejTable.getColumnName(5) + "," + FullAttendancejTable.getColumnName(6));

                for (int x = 0; x < FullAttendancejTable.getRowCount(); x++) {
                    p.println(FullAttendancejTable.getValueAt(x, 0) + "," + FullAttendancejTable.getValueAt(x, 1) + "," + FullAttendancejTable.getValueAt(x, 2) + "," + FullAttendancejTable.getValueAt(x, 3) + "," + FullAttendancejTable.getValueAt(x, 4) + "," + FullAttendancejTable.getValueAt(x, 5) + "," + FullAttendancejTable.getValueAt(x, 6));
                }
                p.flush();
            } catch (Exception ex) {
                System.out.println(ex.toString());
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        try {
            Rectangle pageSize = new Rectangle(PageSize.A4.rotate());
            pageSize.setBackgroundColor(new BaseColor(135, 206, 250));
            pageSize.setBorder(Rectangle.BOX);
            pageSize.setBorderWidth(10f);
            Document doc = new Document(pageSize);
            PdfWriter.getInstance(doc, new FileOutputStream("AttendanceReport.pdf"));
            doc.open();

            doc.add(new Paragraph("Attendance Reporting", FontFactory.getFont("Candara", 35, Font.BOLD, BaseColor.BLACK)));
            doc.add(new Paragraph(20f, Chunk.NEWLINE));
            doc.add(new Paragraph("Batch Code: " + jLabel1batchCode.getText().trim()));
            doc.add(new Paragraph(20f, Chunk.NEWLINE));

            FullAttendancejTable.setForeground(Color.WHITE);
            PdfPTable pdfTable = new PdfPTable(FullAttendancejTable.getColumnCount());
            //adding table headers
            for (int i = 0; i < FullAttendancejTable.getColumnCount(); i++) {
                pdfTable.addCell(FullAttendancejTable.getColumnName(i));
            }
            //extracting data from the JTable and inserting it to PdfPTable
            for (int rows = 0; rows < FullAttendancejTable.getRowCount(); rows++) {
                for (int cols = 0; cols < FullAttendancejTable.getColumnCount(); cols++) {
                    pdfTable.addCell(FullAttendancejTable.getModel().getValueAt(rows, cols).toString());

                }
            }
            doc.add(pdfTable);
            doc.close();
            JOptionPane.showMessageDialog(null, "Attendance Report Saved");

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        // TODO add your handling code here:

        clearing();
        /**
         * Filling jTable through Search
         */
        try {
            DefaultTableModel dt = (DefaultTableModel) FullAttendancejTable.getModel();

            ResultSet rs = c.st.executeQuery("select attend_date as 'Attendance Date', std_id as 'Student ID', std_name as 'Student Name' , std_batch_code as 'Batch Code', std_book as 'Book', std_book_session as 'Book Session', std_status as 'Status' from std_attend where " + jComboBox1.getSelectedItem() + " like '%" + jTextField1.getText().trim() + "%' and std_batch_code = '" + jLabel1batchCode.getText().trim() + "'");
            while (rs.next()) {
                dt.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            }
            
            FullAttendancejTable.setModel(dt);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        //Closing Frame
        try {
            int response = JOptionPane.showConfirmDialog(null, "You have clicked Exit. \n Do you want to close the window?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if (response == JOptionPane.YES_OPTION) {

                LoginFrame lf = new LoginFrame();
                lf.show();
                this.dispose();
            } else if (response == JOptionPane.NO_OPTION) {
            } else if (response == JOptionPane.CLOSED_OPTION) {
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.toString());
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jPanelReport.setVisible(false);
        TeacherInternalFrame tif = new TeacherInternalFrame();
        jDesktopPane1.add(tif);
        tif.show();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        SettingInternalFrame sif = new SettingInternalFrame();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(sif);
        sif.show();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FullAttendancejTable;
    private javax.swing.JLabel HorizontalPanel;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel1batchCode;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelReportPanelBG;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
